package no.f12.codenavigator.navigation.deadcode

import no.f12.codenavigator.navigation.ClassName
import no.f12.codenavigator.navigation.callgraph.MethodRef
import no.f12.codenavigator.navigation.createClassReader
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.io.File

/**
 * Scans compiled class files for JVM bridge methods (ACC_BRIDGE flag).
 *
 * Bridge methods are generated by the JVM to support generic type erasure
 * and covariant return types. They forward to the real implementation and
 * are never called directly in source code. Dead code analysis uses this
 * to filter them out, since they are compiler-generated and not meaningful
 * dead code candidates.
 */
object BridgeMethodDetector {

    fun scanAll(classDirectories: List<File>): Set<MethodRef> {
        val result = mutableSetOf<MethodRef>()

        for (dir in classDirectories) {
            if (!dir.exists()) continue
            dir.walkTopDown()
                .filter { it.isFile && it.extension == "class" }
                .forEach { classFile ->
                    try {
                        result.addAll(detect(classFile))
                    } catch (_: Exception) {
                        // Skip files we can't read
                    }
                }
        }

        return result
    }

    private fun detect(classFile: File): Set<MethodRef> {
        val reader = createClassReader(classFile)
        var className = ClassName("")
        val bridges = mutableSetOf<MethodRef>()

        reader.accept(
            object : ClassVisitor(Opcodes.ASM9) {
                override fun visit(
                    version: Int,
                    access: Int,
                    name: String,
                    signature: String?,
                    superName: String?,
                    interfaces: Array<out String>?,
                ) {
                    className = ClassName.fromInternal(name)
                }

                override fun visitMethod(
                    access: Int,
                    name: String,
                    descriptor: String,
                    signature: String?,
                    exceptions: Array<out String>?,
                ): MethodVisitor? {
                    if (access and Opcodes.ACC_BRIDGE != 0) {
                        bridges.add(MethodRef(className, name))
                    }
                    return null
                }
            },
            ClassReader.SKIP_CODE or ClassReader.SKIP_FRAMES,
        )

        return bridges
    }
}
