package no.f12.codenavigator

object HelpText {
    fun generate(): String = buildString {
        appendLine("=== code-navigator plugin ===")
        appendLine()
        appendLine("Available tasks:")
        appendLine()
        appendLine("  cnavHelp")
        appendLine("    Shows this help text.")
        appendLine("    Usage: ./gradlew cnavHelp")
        appendLine()
        appendLine("  cnavListClasses")
        appendLine("    Lists all classes in the project and their source files.")
        appendLine("    Scans compiled bytecode from the main source set.")
        appendLine("    Usage: ./gradlew cnavListClasses")
        appendLine()
        appendLine("  cnavFindClass")
        appendLine("    Searches for classes matching a regex pattern.")
        appendLine("    Matches against both class name and source file path (case-insensitive).")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against class names and source paths")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=Service")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=\".*Reset.*\"")
        appendLine("    Usage: ./gradlew cnavFindClass -Ppattern=\"domain\\..*\"")
        appendLine()
        appendLine("  cnavFindSymbol")
        appendLine("    Searches for symbols (methods, fields) matching a regex pattern.")
        appendLine("    Matches against package, class name, symbol name, and source file (case-insensitive).")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class generated methods.")
        appendLine("    Output columns: Package | Class | Symbol | Kind | Source File")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against symbol information")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=resetPassword")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=\".*Service.*\"")
        appendLine("    Usage: ./gradlew cnavFindSymbol -Ppattern=\"find.*\"")
        appendLine()
        appendLine("  cnavCallers")
        appendLine("    Shows who calls a given method, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callers transitively.")
        appendLine("    Parameters:")
        appendLine("      -Pmethod=<regex>  (required) Regex to match against Class.method names")
        appendLine("      -Pdepth=<N>       (optional, default 3) Maximum depth of caller tree")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=resetPassword")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=\".*Service\\.find.*\"")
        appendLine("    Usage: ./gradlew cnavCallers -Pmethod=\"Repo\\.save\" -Pdepth=5")
        appendLine()
        appendLine("  cnavCallees")
        appendLine("    Shows what a method calls, displayed as an indented tree.")
        appendLine("    Scans compiled bytecode to build a call graph, then walks callees transitively.")
        appendLine("    Parameters:")
        appendLine("      -Pmethod=<regex>  (required) Regex to match against Class.method names")
        appendLine("      -Pdepth=<N>       (optional, default 3) Maximum depth of callee tree")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=resetPassword")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=\".*Controller\\.handle.*\"")
        appendLine("    Usage: ./gradlew cnavCallees -Pmethod=\"Service\\.create\" -Pdepth=5")
        appendLine()
        appendLine("  cnavClass")
        appendLine("    Shows class signature: fields, methods, superclass, and implemented interfaces.")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class boilerplate.")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against class names")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=ResetPasswordService")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=\".*Client\"")
        appendLine("    Usage: ./gradlew cnavClass -Ppattern=\"domain\\.DomainError\"")
        appendLine()
        appendLine("  cnavInterfaces")
        appendLine("    Finds classes that implement a given interface.")
        appendLine("    Scans compiled bytecode to build an interface-to-implementors map.")
        appendLine("    Parameters:")
        appendLine("      -Ppattern=<regex>  (required) Regex to match against interface names")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=Repository")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=\".*Client\"")
        appendLine("    Usage: ./gradlew cnavInterfaces -Ppattern=\"services\\.interfaces\\..*\"")
        appendLine()
        appendLine("  cnavDeps")
        appendLine("    Shows package-level dependencies — which packages call into which other packages.")
        appendLine("    Aggregates the call graph by package, excluding self-dependencies.")
        appendLine("    Without parameters, shows all packages. With -Ppackage, filters to matching packages.")
        appendLine("    Parameters:")
        appendLine("      -Ppackage=<regex>  (optional) Regex to match against package names")
        appendLine("    Usage: ./gradlew cnavDeps")
        appendLine("    Usage: ./gradlew cnavDeps -Ppackage=services")
        appendLine("    Usage: ./gradlew cnavDeps -Ppackage=\"ktor\\.routes\"")
    }
}
