package no.f12.codenavigator

import no.f12.codenavigator.navigation.annotation.FrameworkPresets
import no.f12.codenavigator.registry.BuildTool
import no.f12.codenavigator.registry.TaskCategory
import no.f12.codenavigator.registry.TaskDef
import no.f12.codenavigator.registry.TaskRegistry

object AgentHelpText {
    private val VALID_SECTIONS = setOf("install", "setup", "workflow", "interpretation", "schemas", "extraction", "recommendations")

    fun generate(tool: BuildTool = BuildTool.GRADLE, section: String? = null): String = when (section) {
        null -> generateCompact(tool)
        "install" -> generateInstall(tool)
        "setup" -> generateSetup(tool)
        "workflow" -> generateWorkflow(tool)
        "interpretation" -> generateInterpretation(tool)
        "schemas" -> generateSchemas(tool)
        "extraction" -> generateExtraction(tool)
        "recommendations" -> generateRecommendations(tool)
        else -> "Unknown section: '$section'. Valid sections: ${VALID_SECTIONS.sorted().joinToString(", ")}"
    }

    private fun generateInstall(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        val pluginId = when (tool) {
            BuildTool.GRADLE -> "no.f12.code-navigator"
            BuildTool.MAVEN -> "code-navigator-maven-plugin"
        }
        val pluginType = when (tool) {
            BuildTool.GRADLE -> "Gradle"
            BuildTool.MAVEN -> "Maven"
        }

        appendLine("## Code Navigator (cnav)")
        appendLine()
        appendLine("$pluginType plugin (`$pluginId`) that analyzes compiled bytecode and git history.")
        appendLine()
        appendLine("IMPORTANT: Always use cnav instead of grep/ripgrep for these tasks:")
        appendLine("- Before moving/renaming/deleting a class or file: Run ${u("find-usages", p("type", "ClassName"))} to find ALL references (including implicit same-package usages that grep will miss).")
        appendLine("- Finding who calls a method: ${u("find-callers", p("pattern", "methodName"))}")
        appendLine("- Finding implementations of an interface: ${u("find-interfaces", p("pattern", "InterfaceName"))}")
        appendLine("- Understanding dependencies between packages: ${t("package-deps")} or ${t("dsm")}")
        appendLine("- Assessing impact of a change: ${u("changed-since", p("ref", "main"))}")
        appendLine()
        appendLine("Bytecode analysis is complete and handles all syntax variants (implicit imports, extension")
        appendLine("functions, companion objects, lambdas) in a single query. Grep-based searches miss implicit")
        appendLine("same-package references and require guessing import patterns.")
        appendLine()
        appendLine("Only use grep/ripgrep when searching for string literals, comments, or text patterns")
        appendLine("that don't correspond to type/method/field references.")
        appendLine()
        appendLine("Run ${tool.usage("agent-help")} for full usage instructions optimized for AI agents.")
        appendLine("Navigation tasks analyze compiled bytecode and require classes to be built.")
        appendLine("Git history tasks work without compilation.")
        appendLine("Run ${tool.usage("help")} to see all available tasks and their parameters.")
    }

    private fun generateSetup(tool: BuildTool): String = buildString {
        appendLine("=== code-navigator: Setup ===")
        appendLine()
        appendLine("### Permissions")
        appendLine()
        appendLine("If a cnav command triggers a Bash approval prompt, create a permission rule")
        appendLine("so future cnav commands run without prompting:")
        appendLine("1. Copy the command string shown in the approval prompt")
        appendLine("2. Keep everything up to and including `cnav`, replace the rest with `*`")
        appendLine("3. Add as a Bash allow rule in `.claude/settings.local.json`")
        appendLine()
        when (tool) {
            BuildTool.GRADLE -> {
                appendLine("Example — if the prompt shows:")
                appendLine("  `./gradlew cnavListClasses -Pllm=true`")
                appendLine("Add: `\"Bash(./gradlew cnav*)\"`")
                appendLine()
                appendLine("If your command has a preamble (e.g. `eval \"\$(mise activate bash)\" && ./gradlew cnavListClasses ...`),")
                appendLine("include the preamble in the rule: `\"Bash(eval \\\"\\$(mise activate bash)\\\" && ./gradlew cnav*)\"`")
            }
            BuildTool.MAVEN -> {
                appendLine("Example — if the prompt shows:")
                appendLine("  `mvn cnav:find-usages -Dtype=Foo -Dllm=true`")
                appendLine("Add: `\"Bash(mvn cnav:*)\"`")
            }
        }
    }

    private fun generateCompact(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        val pf = { name: String -> tool.paramFlag(name) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        val pluginType = when (tool) {
            BuildTool.GRADLE -> "Gradle"
            BuildTool.MAVEN -> "Maven"
        }

        appendLine("=== code-navigator: AI Agent Guide ===")
        appendLine()
        appendLine("code-navigator is a $pluginType plugin for reliable code navigation and code smell analysis.")
        appendLine("It gives you structural and behavioral insight into a codebase without reading source files.")
        appendLine("Navigation queries return accurate, complete results in a single tool call —")
        appendLine("No iterative searching needed. Be correct on the first response.")
        appendLine("All tasks support ${p("llm", "true")} for compact, token-efficient output.")
        appendLine("All tasks also support ${p("format", "json")} for structured, parseable output.")
        appendLine()
        appendLine("--- When to Use What ---")
        appendLine()
        appendLine("IMPORTANT: Always use code-navigator instead of grep/ripgrep for these tasks:")
        appendLine("- Tracing call chains — ${t("find-callers")}/${t("find-callees")} resolve actual invocations")
        appendLine("  through interfaces and inheritance.")
        appendLine("- Before moving/renaming/deleting a class — ${t("find-usages")} finds ALL references")
        appendLine("  including implicit same-package usages that grep will miss.")
        appendLine("- Understanding dependencies — ${t("package-deps")}/${t("dsm")} give accurate package-level")
        appendLine("  coupling.")
        appendLine("- Finding interface implementations — ${t("find-interfaces")} resolves polymorphism.")
        appendLine("- Migration planning — ${t("find-usages")} finds all call sites, field accesses, and type")
        appendLine("  references to external APIs.")
        appendLine("- Inspecting class structure — ${t("class-detail")} shows fields, methods, supertypes, annotations")
        appendLine("  without reading source files.")
        appendLine("- Assessing impact of a change — ${t("changed-since")} shows blast radius vs a branch or tag.")
        appendLine()
        appendLine("Bytecode analysis handles all syntax variants (implicit imports, extension functions,")
        appendLine("companion objects, lambdas) in a single query.")
        appendLine()
        appendLine("Use grep/glob when:")
        appendLine("- Searching for string patterns, variable names, or text in comments")
        appendLine("- Finding files by name")
        appendLine("- Reading implementation logic (method bodies)")
        appendLine()
        appendLine("--- Common Questions → Which Task ---")
        appendLine()
        appendLine("  \"Where is type X used?\"")
        appendLine("    → ${u("find-usages", p("type", "X"))}")
        appendLine()
        appendLine("  \"Where is field X read or written?\"")
        appendLine("    → ${u("find-usages", p("owner-class", "com.example.Config"), p("field", "timeout"))}")
        appendLine()
        appendLine("  \"Who calls method X?\"")
        appendLine("    → ${u("find-callers", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"What does class X look like?\"")
        appendLine("    → ${u("class-detail", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"What calls does method X make?\"")
        appendLine("    → ${u("find-callees", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"Who implements interface X?\"")
        appendLine("    → ${u("find-interfaces", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"What does class X extend/implement?\"")
        appendLine("    → ${u("type-hierarchy", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"What depends on package X?\"")
        appendLine("    → ${u("package-deps", p("package", "X"), p("reverse", "true"))}")
        appendLine()
        appendLine("  \"What does package X import?\" / \"What are the dependencies between packages?\"")
        appendLine("    → ${u("package-deps")} for per-package edges, ${t("dsm")} for the full matrix")
        appendLine("    # Bytecode analysis — more accurate than source-level import scanning")
        appendLine()
        appendLine("  \"Is there dead code?\"  → ${u("dead")}")
        appendLine()
        appendLine("  \"What are the most important types?\"  → ${u("rank")}")
        appendLine()
        appendLine("  \"Which files change the most?\"  → ${u("hotspots")}")
        appendLine()
        appendLine("  \"Which source files are the largest?\" / \"How big are my files?\"")
        appendLine("    → ${u("size")}")
        appendLine("    # Lists source files by line count; use ${p("over", "100")} to filter small files")
        appendLine()
        appendLine("  \"Rename a method parameter?\"")
        appendLine("    → ${u("rename-param", p("target-class", "com.example.Service"), p("method", "find"), p("param", "limit"), p("new-name", "maxResults"))}")
        appendLine("    # Applies by default; add ${pf("preview")} for dry-run")
        appendLine()
        appendLine("  \"Rename a method?\"")
        appendLine("    → ${u("rename-method", p("target-class", "com.example.Service"), p("method", "find"), p("new-name", "search"))}")
        appendLine("    # Renames method + call sites + interface implementations; add ${pf("preview")} for dry-run")
        appendLine()
        appendLine("  \"Move a class to a different package?\"")
        appendLine("    → ${u("move-class", p("target-class", "com.example.services.UserService"), p("new-package", "com.example.domain"))}")
        appendLine("    # Moves file + updates package declaration + all imports; add ${pf("preview")} for dry-run")
        appendLine()
        appendLine("  \"Rename a class?\"")
        appendLine("    → ${u("move-class", p("target-class", "com.example.services.UserService"), p("new-name", "AccountService"))}")
        appendLine("    # Renames class + updates all references; use ${p("new-package", "")} to also move; add ${pf("preview")} for dry-run")
        appendLine()
        appendLine("  \"Rename a property?\"")
        appendLine("    → ${u("rename-property", p("target-class", "com.example.UserProfile"), p("property", "fullName"), p("new-name", "displayName"))}")
        appendLine("    # Renames val/var property + all access sites, constructor named args, copy() calls; add ${pf("preview")} for dry-run")
        appendLine()
        appendLine("  \"Where is string X hardcoded?\"")
        appendLine("    → ${u("find-string-constant", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"Which classes use annotation X?\"")
        appendLine("    → ${u("annotations", p("pattern", "X"))}")
        appendLine()
        appendLine("  \"Which methods have annotation X?\"")
        appendLine("    → ${u("annotations", p("pattern", "X"), p("methods", "true"))}")
        appendLine()
        appendLine("  \"What's the blast radius of my changes?\"")
        appendLine("    → ${u("changed-since", p("ref", "main"))}")
        appendLine()
        appendLine("  \"Give me everything about class X\" / \"Full context for X\"")
        appendLine("    → ${u("context", p("pattern", "X"))}")
        appendLine("    # Returns class detail + callers + callees + interfaces in one call")
        appendLine()
        appendLine("  \"How far apart are coupled packages?\"")
        appendLine("    → ${u("distance")}")
        appendLine("    # Shows structural distance between packages that depend on each other")
        appendLine()
        appendLine("  \"How tightly coupled are packages?\" / \"What kind of dependencies between packages?\"")
        appendLine("    → ${u("strength")}")
        appendLine("    # Classifies dependency edges as CONTRACT, MODEL, or FUNCTIONAL")
        appendLine()
        appendLine("  \"Overall coupling health?\" / \"Which package pairs are problematic?\"")
        appendLine("    → ${u("balance")}")
        appendLine("    # combines ${t("strength")} × ${t("distance")} × ${t("volatility")} into a single verdict per package pair")
        appendLine()
        appendLine("  \"Does my code follow layer rules?\" / \"Are there layer violations?\"")
        appendLine("    → ${u("layer-check")}")
        appendLine("    # Checks hexagonal architecture layer conformance against .cnav-layers.json")
        appendLine("    # Layers are defined by class name patterns (e.g. *Controller, *Service, *)")
        appendLine("    # Kt and Test suffixes are stripped automatically — write *Route, not *RouteKt")
        appendLine("    # testInfrastructure: true on a layer allows test classes to depend on it freely")
        appendLine("    # Use ${p("init", "true")} to generate a starter config from detected patterns")
        appendLine()
        appendLine("--- Task Reference ---")
        appendLine()
        appendTaskReference(tool)
        appendLine()
        appendLine("--- Global Parameters ---")
        appendLine()
        appendGlobalParameters(tool)
        appendLine()
        appendLine("--- Pattern Matching ---")
        appendLine()
        appendLine("All patterns are Java regex, case-insensitive, and substring-matched.")
        appendLine("Simple class names work: 'Owner' matches 'org.example.owner.Owner'.")
        appendLine("FQN patterns work too: 'owner\\.Owner' matches the full qualified name.")
        appendLine()
        appendLine("CamelCase shorthand: at camelCase boundaries, .* is inserted automatically.")
        appendLine("  OwnCont → Own.*Cont  (matches OwnerController, etc.)")
        appendLine()
        appendLine("Enhanced params (auto camelCase expansion): pattern, owner-class, type")
        appendLine("Plain regex params (no expansion): method, field, filter, exclude, find-string-constant's pattern")
        appendLine()
        appendLine("--- Tips for Optimal Results ---")
        appendLine()
        appendLine("- Always use ${p("llm", "true")} for compact output. Omit only for human-readable display.")
        appendLine("- Use ${p("project-only", "true")} to cut noise from JDK/stdlib classes.")
        appendLine("- Chain tasks: find a class → inspect it → trace its callers.")
        appendLine("- Results are cached across calls — subsequent runs in the same build are fast.")
        appendLine("- Run ${u("help")} for full parameter documentation.")
        appendLine()
        appendLine("--- Useful Combinations ---")
        appendLine()
        appendLine("These task combinations answer common questions no single task covers:")
        appendLine("  Refactoring targets: ${t("hotspots")} + ${t("complexity")} + ${t("cycles")}")
        appendLine("  Architecture overview: ${t("dsm")} + ${t("package-deps")} + ${t("cycles")}")
        appendLine("  Change risk: ${t("changed-since")} + ${t("find-callers")}")
        appendLine("  Code review context: ${t("hotspots")} + ${t("authors")} + ${t("churn")}")
        appendLine("  Coupling health: use ${t("balance")} (combines ${t("strength")} × ${t("distance")} × ${t("volatility")})")
        appendLine()
        appendTroubleshooting(tool)
        appendLine()
        appendSectionDirectory(tool)
    }

    private fun generateWorkflow(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        appendLine("=== code-navigator: Recommended Workflow ===")
        appendLine()
        appendLine("1. ORIENT: Get a high-level view of the codebase")
        appendLine("   ${u("package-deps")}                        # package dependency map")
        appendLine("   ${u("dsm")}                         # dependency structure matrix")
        appendLine("   ${u("package-deps", p("format", "json"))}           # same, as JSON")
        appendLine("   ${u("list-classes")}                  # all classes and source files")
        appendLine()
        appendLine("2. FIND: Locate relevant code")
        appendLine("   ${u("find-class", p("pattern", "Service"))}  # find classes by name")
        appendLine("   ${u("find-symbol", p("pattern", "reset"))}   # find methods/fields by name")
        appendLine()
        appendLine("3. INSPECT: Understand a class")
        appendLine("   ${u("class-detail", p("pattern", "ResetPasswordService"))}")
        appendLine("   # Shows fields, methods, superclass, and implemented interfaces")
        appendLine()
        appendLine("4. TRACE: Follow the call graph")
        appendLine("   ${u("find-callers", p("pattern", "resetPassword"), p("maxdepth", "3"), p("project-only", "true"))}  # who calls this?")
        appendLine("   ${u("find-callees", p("pattern", "handleRequest"), p("maxdepth", "3"), p("project-only", "false"))}  # what does this call?")
        appendLine("   # ${p("project-only", "true")} hides JDK/stdlib noise")
        appendLine("   # ${p("maxdepth", "5")} for deeper traversal")
        appendLine()
        appendLine("5. MAP: Understand abstractions")
        appendLine("   ${u("find-interfaces", p("pattern", "Repository"))}")
        appendLine("   # Test source sets are included by default — test fakes/stubs are visible")
        appendLine("   # Use ${p("test-only", "true")} to see only test fakes and stubs")
        appendLine("   ${u("type-hierarchy", p("pattern", "Service"))}")
        appendLine("   # Shows superclass chain upward + implementors downward")
        appendLine()
        appendLine("6. MIGRATE: Find external API usage for migration")
        appendLine("   ${u("find-usages", p("owner-class", "kotlinx.datetime.LocalDate"), p("method", "getMonthNumber"))}")
        appendLine("   ${u("find-usages", p("owner-class", "com.example.Config"), p("field", "timeout"))}  # field reads/writes + property accessors")
        appendLine("   ${u("find-usages", p("type", "kotlinx.datetime.Instant"))}")
        appendLine("   # Find all call sites, field accesses, and type references to external types")
        appendLine()
        appendLine("7. ANALYZE: Git history behavioral analysis (no compilation needed)")
        appendLine("   ${u("hotspots")}                     # most-changed files")
        appendLine("   ${u("coupling")}                     # files that change together")
        appendLine("   ${u("code-age")}                          # time since last change per file")
        appendLine("   ${u("authors")}                      # distinct contributors per file")
        appendLine("   ${u("churn")}                        # lines added/deleted per file")
        appendLine("   # All git tasks accept ${p("after", "YYYY-MM-DD")} (default: 1 year ago)")
        appendLine()
        appendLine("   Source analysis (no compilation needed):")
        appendLine("   ${u("size")}                         # largest source files by line count")
        appendLine("   ${u("size", p("over", "100"))}                # only files over 100 lines")
        appendLine()
        appendLine("8. RANK: Identify structurally important types")
        appendLine("   ${u("rank")}                         # top 50 most important types (PageRank)")
        appendLine("   ${u("rank", p("top", "20"))}                  # top 20")
        appendLine("   ${u("rank", p("project-only", "false"))}        # include external types")
        appendLine()
        appendLine("9. DEAD CODE: Find unreferenced classes and methods")
        appendLine("   Kotlin noise (data class boilerplate, companion objects, coroutine inner classes) is auto-filtered.")
        appendLine("   ${u("dead")}                         # all potential dead code")
        appendLine("   ${u("dead", p("filter", "service"))}             # only show matches")
        appendLine("   ${u("dead", p("exclude", "\"Main|Test\""))}    # exclude entry points")
        appendLine("   ${u("dead", p("exclude", "\"com\\\\.example\\\\.grpc\""))}  # exclude generated packages")
        appendLine("   ${u("dead", p("classes-only", "true"))}         # only unreferenced classes")
        appendLine("   ${u("dead", p("exclude-annotated", "\"RestController,Scheduled\""))}  # skip framework-annotated")
        appendLine("   ${u("dead", p("prod-only", "true"))}              # only items with zero references (production + test)")
        appendLine("   ${u("dead", p("test-only", "true"))}              # only items referenced exclusively from tests")
        appendLine("   ${u("dead", p("treat-as-dead", "spring"))}      # treat Spring-annotated code as potentially dead")
        appendLine("   ${u("dead", p("treat-as-dead", "ALL"))}         # treat all framework-annotated code as potentially dead")
        appendLine()
        appendLine("10. COMPLEXITY: Measure class coupling (fan-in/fan-out)")
        appendLine("   ${u("complexity")}                        # all classes sorted by fan-out")
        appendLine("   ${u("complexity", p("pattern", "Service"))}       # fan-in/out for matching classes")
        appendLine("   ${u("complexity", p("pattern", "\".*Controller\""), p("detail", "true"))} # with call details")
        appendLine()
        appendLine("11. METRICS: Quick project health snapshot")
        appendLine("   ${u("metrics")}                       # summary: classes, packages, fan-in/out, cycles, dead code, hotspots")
        appendLine("   ${u("metrics", p("top", "10"))}                # top 10 hotspots")
        appendLine("   ${u("metrics", p("package-filter", "com.example"))} # scope structural analysis to package")
        appendLine()
        appendLine("12. DISTANCE: Structural distance between coupled packages")
        appendLine("   ${u("distance")}                      # all dependency edges with tree distance")
        appendLine("   ${u("distance", p("top", "20"))}               # top 20 most distant coupled packages")
        appendLine("   ${u("distance", p("package-filter", "com.example"))} # scope to a package prefix")
        appendLine()
        appendLine("13. STRENGTH: Integration strength between coupled packages")
        appendLine("   ${u("strength")}                     # classify all dependency edges")
        appendLine("   ${u("strength", p("top", "20"))}              # top 20 strongest couplings")
        appendLine("   ${u("strength", p("package-filter", "com.example"))} # scope to a package prefix")
        appendLine("   # CONTRACT=interface/abstract, MODEL=data class/record, FUNCTIONAL=concrete class")
        appendLine()
        appendLine("14. VOLATILITY: Package-level change frequency from git history")
        appendLine("   ${u("volatility")}                    # all packages ranked by revision count")
        appendLine("   ${u("volatility", p("top", "20"))}             # top 20 most volatile packages")
        appendLine("   ${u("volatility", p("after", "2024-01-01"))}    # limit to recent history")
        appendLine("   # Maps file-level git hotspots to packages. Key dimension for Balanced Coupling.")
        appendLine()
        appendLine("15. BALANCE: Composite balanced coupling verdict per package pair")
        appendLine("   ${u("balance")}                       # all package pairs with strength × distance × volatility verdict")
        appendLine("   ${u("balance", p("top", "20"))}                # top 20 most problematic pairs")
        appendLine("   ${u("balance", p("package-filter", "com.example"))} # scope to a package prefix")
        appendLine("   # Verdicts: DANGER > OVER_ENGINEERED > TOLERABLE > BALANCED. Requires compilation + git history.")
        appendLine()
        appendLine("16. STRING CONSTANTS: Find hardcoded strings in compiled code")
        appendLine("   ${u("find-string-constant", p("pattern", "\"http://\""))}      # find URLs")
        appendLine("   ${u("find-string-constant", p("pattern", "\"SELECT.*FROM\""))} # find SQL")
        appendLine("   ${u("find-string-constant", p("pattern", "\"password|secret\""))} # find sensitive strings")
        appendLine()
        appendLine("17. ANNOTATIONS: Find classes and methods by annotation")
        appendLine("   ${u("annotations", p("pattern", "RestController"))}          # find all @RestController classes")
        appendLine("   ${u("annotations", p("pattern", "Mapping"), p("methods", "true"))}  # find @*Mapping on classes and methods")
        appendLine("   ${u("annotations", p("pattern", "Scheduled"), p("methods", "true"))} # find all @Scheduled methods")
        appendLine()
        appendLine("18. IMPACT: See what's affected by recent changes")
        appendLine("   ${u("changed-since", p("ref", "main"))}           # blast radius vs main branch")
        appendLine("   ${u("changed-since", p("ref", "v1.2.0"))}          # blast radius since a tag")
        appendLine("   ${u("changed-since", p("ref", "HEAD~5"))}          # blast radius of last 5 commits")
        appendLine("   # Shows changed classes, their callers, and unresolved files (non-class changes)")
        appendLine()
        appendLine("--- Useful Combinations ---")
        appendLine()
        appendLine("These task combinations answer common questions no single task covers:")
        appendLine("  Refactoring targets: ${t("hotspots")} + ${t("complexity")} + ${t("cycles")}")
        appendLine("    Files that change often, have high fan-out, and sit in dependency cycles.")
        appendLine("  Architecture overview: ${t("dsm")} + ${t("package-deps")} + ${t("cycles")}")
        appendLine("    Structural map: dependency matrix, per-package edges, and tangles.")
        appendLine("  Change risk: ${t("changed-since")} + ${t("find-callers")}")
        appendLine("    Blast radius of recent changes, then trace deeper into affected call chains.")
        appendLine("  Code review context: ${t("hotspots")} + ${t("authors")} + ${t("churn")}")
        appendLine("    Behavioral history: what changes often, who owns it, how much churn.")
        appendLine("  Coupling health: use ${t("balance")} (combines ${t("strength")} × ${t("distance")} × ${t("volatility")})")
    }

    private fun generateInterpretation(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }

        appendLine("=== code-navigator: Result Interpretation ===")
        appendLine()
        appendLine("Fan-in (${t("complexity")} / ${t("rank")}):")
        appendLine("- High fan-in on a concrete class (>20 callers) → possible god object or central")
        appendLine("  service. Investigate whether it has too many responsibilities.")
        appendLine("- High fan-in on an interface or abstract class → normal. Core domain abstractions")
        appendLine("  are meant to be widely depended on.")
        appendLine("- High fan-in on a repository → normal. Repositories are shared infrastructure.")
        appendLine()
        appendLine("Fan-out (${t("complexity")}):")
        appendLine("- High fan-out (>15 distinct dependencies) → class depends on too many things.")
        appendLine("  Candidate for decomposition — split into focused collaborators.")
        appendLine("- High fan-out in a formatter or controller → often acceptable. These are")
        appendLine("  integration points that coordinate many domain objects.")
        appendLine()
        appendLine("Dead code (${t("dead")}):")
        appendLine("- Each result includes a confidence level: HIGH, MEDIUM, or LOW.")
        appendLine("  HIGH = unreferenced in both production and test code.")
        appendLine("  MEDIUM = unreferenced in production but referenced in test code.")
        appendLine("  LOW = has framework annotations (likely invoked via reflection).")
        appendLine("- Each result includes a reason: NO_REFERENCES or TEST_ONLY.")
        appendLine("  NO_REFERENCES = no incoming references at all.")
        appendLine("  TEST_ONLY = referenced only in test code, not production.")
        appendLine("- Use ${p("prod-only", "true")} to hide TEST_ONLY items and focus on truly unreferenced code.")
        appendLine("- Use ${p("test-only", "true")} to show only TEST_ONLY items (code referenced exclusively from tests).")
        appendLine("- All framework presets are active by default — no configuration needed for Spring, Quarkus, or other frameworks.")
        appendLine("  Use ${p("treat-as-dead", "<preset>")} to treat a specific framework's annotated code as potentially dead.")
        appendLine("  Available presets: ${FrameworkPresets.availablePresets().sorted().joinToString(", ")}.")
        appendLine("  Use ${p("treat-as-dead", "ALL")} to remove all framework protections.")
        appendLine("  Composite presets: 'quarkus' includes jaxrs + cdi + microprofile + jpa + jakarta + validation + jackson.")
        appendLine("  Entry-point annotations (e.g. @GetMapping, @Scheduled) → excluded from results.")
        appendLine("  Modifier annotations (e.g. @Transactional, @Cacheable) → reported with LOW confidence.")
        appendLine("  Supertype entry points (e.g. JpaRepository, PanacheRepository) → excluded from results.")
        appendLine("  Receiver type entry points (e.g. Ktor Route/Application extension functions) → excluded from results.")
        appendLine("- Use -Pexclude-annotated to suppress additional entry points not covered by presets.")
        appendLine("- Use ${p("exclude", "<regex>")} to exclude entire packages (e.g. generated protobuf code).")
        appendLine("- Companion object members and data class copy()/componentN() are auto-filtered.")
        appendLine()
        appendLine("Change coupling (${t("coupling")}):")
        appendLine("- High coupling degree (>60%) with many shared revisions → strong implicit dependency.")
        appendLine("  Consider extracting shared logic or making the dependency explicit.")
        appendLine("- High coupling degree but few shared revisions (<5) → may be coincidence.")
        appendLine("  Wait for more data before acting.")
        appendLine("- Test file coupled with its production file → expected, not a problem.")
        appendLine()
        appendLine("Hotspots (${t("hotspots")}):")
        appendLine("- Files with high revision count AND structural problems (high fan-out, cycles)")
        appendLine("  are priority refactoring targets — they change often and are hard to change safely.")
        appendLine("- Files with high revision count but clean structure → active development, not a problem.")
        appendLine()
        appendLine("DSM — Dependency Structure Matrix (${t("dsm")}):")
        appendLine("- Read as: row depends on column. Cell value = number of dependency references.")
        appendLine("- Cells below the diagonal = forward dependencies (normal, expected).")
        appendLine("- Cells above the diagonal = backward dependencies (potential cycles — review these).")
        appendLine("- A clean DSM is lower-triangular: all non-zero cells sit below the diagonal.")
        appendLine("- Dense rows (many non-zero cells) → package depends on too many others. Candidate")
        appendLine("  for decomposition or layering review.")
        appendLine("- Dense columns → package is depended on by many others (high fan-in). If it is a")
        appendLine("  stable abstraction (interface, domain model) this is fine. If it is an implementation")
        appendLine("  detail, it signals hidden coupling.")
        appendLine("- Symmetric pairs (A→B and B→A both non-zero) → mutual dependency / cycle between")
        appendLine("  packages. The DSM highlights these with a WARNING block listing class-level edges.")
        appendLine("- Use ${p("dsm-depth", "2")} to collapse deep packages and see higher-level structure.")
        appendLine()
        appendLine("Cycles (${t("cycles")}):")
        appendLine("- Uses Tarjan's algorithm to find strongly connected components (SCCs) in the")
        appendLine("  package dependency graph. Each SCC is a group of packages that mutually depend")
        appendLine("  on each other, directly or transitively.")
        appendLine("- A 2-package cycle (A↔B) → often fixable by inverting one dependency or extracting")
        appendLine("  a shared interface.")
        appendLine("- A large cycle (3+ packages) → architectural tangle. Map the edges to find the")
        appendLine("  weakest link (fewest references) and break there first.")
        appendLine("- Cycles in leaf packages (utilities, helpers) are low risk. Cycles spanning")
        appendLine("  architectural layers (api↔persistence, domain↔infra) are high risk.")
        appendLine()
        appendLine("Distance (${t("distance")}):")
        appendLine("- Structural distance = tree hops between two coupled packages in the package hierarchy.")
        appendLine("  distance=1 means sibling or parent/child packages (close, expected).")
        appendLine("  distance=2-3 means packages in nearby but different subtrees (normal for cross-cutting")
        appendLine("  concerns like api→service or service→persistence).")
        appendLine("  distance>=4 means packages in very different parts of the tree (long-range coupling —")
        appendLine("  review whether an interface or shared module should mediate).")
        appendLine("- High distance + high dependency count → tightly coupled across a wide gap. Priority")
        appendLine("  candidate for introducing an abstraction boundary or co-locating the packages.")
        appendLine("- Low distance + low dependency count → normal, healthy locality.")
        appendLine("- Use ${p("top", "20")} to focus on the most distant couplings first.")
        appendLine()
        appendLine("Strength (${t("strength")}):")
        appendLine("- Integration strength classifies how tightly coupled two packages are based on the")
        appendLine("  type of knowledge shared (Balanced Coupling theory, Vlad Khononov).")
        appendLine("  CONTRACT = depends on interface or abstract class (loosest coupling, easiest to change).")
        appendLine("  MODEL = depends on data class or record (medium coupling, shared data structure).")
        appendLine("  FUNCTIONAL = depends on concrete class (tightest coupling, hardest to change).")
        appendLine("- When a package pair has edges at multiple levels, the strongest level wins.")
        appendLine("- FUNCTIONAL dependencies between distant packages → priority refactoring target.")
        appendLine("  Consider introducing an interface or shared data model.")
        appendLine("- CONTRACT dependencies → healthy. Packages couple through abstractions.")
        appendLine("- Combine with ${t("distance")}: high distance + FUNCTIONAL strength = worst case.")
        appendLine("  Low distance + CONTRACT strength = best case.")
        appendLine()
        appendLine("Balance (${t("balance")}):")
        appendLine("- Composite verdict combining strength × distance × volatility per package pair.")
        appendLine("  DANGER = tightly coupled (FUNCTIONAL) + high distance + high volatility. Highest risk.")
        appendLine("  OVER_ENGINEERED = loosely coupled nearby packages. Consider simplifying or merging.")
        appendLine("  TOLERABLE = poor modularity but low volatility. Monitor for changes.")
        appendLine("  BALANCED = good modularity (strength and distance are complementary).")
        appendLine("- DANGER pairs are priority refactoring targets: co-locate packages or introduce contracts.")
        appendLine("- OVER_ENGINEERED pairs may indicate unnecessary abstraction layers between close packages.")
        appendLine("- Use ${t("balance")} as a starting point, then drill into ${t("strength")}, ${t("distance")},")
        appendLine("  and ${t("volatility")} for individual dimensions.")
        appendLine()
        appendLine("Rank (${t("rank")}):")
        appendLine("- Uses PageRank on the call graph to find structurally important types.")
        appendLine("- High rank = many transitive dependents. A change here has a large blast radius.")
        appendLine("- Top-ranked types that are concrete classes → candidates for interface extraction")
        appendLine("  to reduce coupling.")
        appendLine("- Top-ranked types that are interfaces or abstract classes → healthy; they are")
        appendLine("  designed to be widely depended on.")
        appendLine("- Compare rank with fan-in (${t("complexity")}): rank captures transitive importance,")
        appendLine("  fan-in captures direct dependents. A class with moderate fan-in but high rank is")
        appendLine("  a hidden linchpin.")
        appendLine()
        appendLine("Code age (${t("code-age")}):")
        appendLine("- Shows how many months since each file was last changed.")
        appendLine("- Old + stable + clean structure → mature code, leave it alone.")
        appendLine("- Old + frequently appearing in hotspots → legacy burden. Prioritize refactoring.")
        appendLine("- Young code across many files → active development area, expect churn.")
        appendLine()
        appendLine("Churn (${t("churn")}):")
        appendLine("- Shows lines added, deleted, and net change per file over git history.")
        appendLine("- High churn (large added+deleted) with low net change → code is being rewritten")
        appendLine("  repeatedly. Investigate design instability or unclear requirements.")
        appendLine("- High churn concentrated in a few files → these are volatility hotspots. Cross-reference")
        appendLine("  with ${t("complexity")} to see if they also have structural problems.")
        appendLine("- High churn in test files → often normal; tests evolve with the code.")
        appendLine()
        appendLine("Author analysis (${t("authors")}):")
        appendLine("- Files touched by many distinct authors → higher coordination cost and defect risk.")
        appendLine("- A module with 1-2 authors → strong ownership, lower defect rate.")
        appendLine("- Use alongside ${t("hotspots")} to find files that are both heavily changed and")
        appendLine("  lack clear ownership.")
        appendLine()
        appendLine("Metrics snapshot (${t("metrics")}):")
        appendLine("- Quick project health snapshot: package count, class count, dependency counts,")
        appendLine("  cycle count, average fan-in/fan-out.")
        appendLine("- Use as a baseline before and after refactoring to measure structural improvement.")
        appendLine("- Rising cycle count or average fan-out over time → architecture is degrading.")
        appendLine("- Falling cycle count → layering improvements are taking effect.")
        appendLine()
        appendLine("Layer check (${t("layer-check")}):")
        appendLine("- Config file (.cnav-layers.json) defines layers top-to-bottom = outermost to innermost.")
        appendLine("- Each layer has name patterns (globs: *Controller, *Service, *). First match wins.")
        appendLine("- Kt and Test suffixes are stripped automatically before matching. Write *Route, not *RouteKt.")
        appendLine("  OrderRouteKt matches *Route. OrderServiceTest matches *Service.")
        appendLine("- OUTWARD violation: class depends on a class in a higher (outer) layer.")
        appendLine("  Fix by introducing an interface in the lower layer or moving the dependency.")
        appendLine("- PEER violation: class exceeds peerLimit for same-layer dependencies.")
        appendLine("  Default peerLimit=0 (no peer deps). Set peerLimit=-1 for unlimited.")
        appendLine("- Common pattern: test classes reaching wiring layer for DI setup (TestContext).")
        appendLine("  Add testInfrastructure: true to the wiring layer to exempt test classes from OUTWARD checks.")
        appendLine("  Production code depending on a testInfrastructure layer is still a violation.")
        appendLine("- If a class doesn't match any specific pattern, add it explicitly to the right layer.")
        appendLine("  Example: E2ETestBase doesn't end in Test — add \"E2ETestBase\" to a test/wiring layer.")
    }

    private fun generateSchemas(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }

        appendLine("=== code-navigator: JSON Schemas ===")
        appendLine()
        appendLine("${t("list-classes")} / ${t("find-class")}:")
        appendLine("  [{\"className\": \"com.example.Foo\", \"sourceFile\": \"Foo.kt\", \"sourcePath\": \"com/example/Foo.kt\"}]")
        appendLine()
        appendLine("${t("find-symbol")}:")
        appendLine("  [{\"package\": \"com.example\", \"class\": \"Service\", \"symbol\": \"doWork\", \"kind\": \"method\", \"sourceFile\": \"Service.kt\"}]")
        appendLine()
        appendLine("${t("class-detail")}:")
        appendLine("  [{\"className\": \"...\", \"sourceFile\": \"...\", \"superClass\": \"...\",")
        appendLine("    \"annotations\": [{\"name\": \"...\", \"parameters\": {}}],")
        appendLine("    \"interfaces\": [\"...\"], \"fields\": [{\"name\": \"...\", \"type\": \"...\", \"annotations\": [...]}],")
        appendLine("    \"methods\": [{\"name\": \"...\", \"parameters\": [\"...\"], \"returnType\": \"...\", \"annotations\": [...]}]}]")
        appendLine()
        appendLine("${t("find-callers")} / ${t("find-callees")}:")
        appendLine("  [{\"method\": \"com.example.Service.doWork\", \"sourceFile\": \"Service.kt\",")
        appendLine("    \"children\": [{\"method\": \"...\", \"sourceFile\": \"...\", \"children\": [...]}]}]")
        appendLine()
        appendLine("${t("find-interfaces")}:")
        appendLine("  [{\"interface\": \"com.example.Repository\",")
        appendLine("    \"implementors\": [{\"className\": \"com.example.SqlRepo\", \"sourceFile\": \"SqlRepo.kt\"}]}]")
        appendLine()
        appendLine("${t("type-hierarchy")}:")
        appendLine("  [{\"className\": \"com.example.SqlRepo\", \"sourceFile\": \"SqlRepo.kt\",")
        appendLine("    \"supertypes\": [{\"className\": \"com.example.Repository\", \"kind\": \"INTERFACE\", \"supertypes\": []}],")
        appendLine("    \"implementors\": []}]")
        appendLine()
        appendLine("${t("package-deps")}:")
        appendLine("  [{\"package\": \"com.example.services\", \"dependencies\": [\"com.example.domain\"]}]")
        appendLine("  With ${p("reverse", "true")}: \"dependents\" replaces \"dependencies\"")
        appendLine()
        appendLine("${t("find-usages")}:")
        appendLine("  [{\"callerClass\": \"com.example.MyService\", \"callerMethod\": \"process\",")
        appendLine("    \"targetOwner\": \"kotlinx.datetime.LocalDate\", \"targetMethod\": \"getMonthNumber\",")
        appendLine("    \"kind\": \"method_call\", \"sourceFile\": \"MyService.kt\"}]")
        appendLine()
        appendLine("${t("rank")}:")
        appendLine("  [{\"className\": \"com.example.Core\", \"rank\": 0.42, \"inDegree\": 5, \"outDegree\": 2}]")
        appendLine()
        appendLine("${t("dead")}:")
        appendLine("  [{\"className\": \"com.example.Orphan\", \"kind\": \"class\", \"sourceFile\": \"Orphan.kt\", \"confidence\": \"high\", \"reason\": \"NO_REFERENCES\"},")
        appendLine("   {\"className\": \"com.example.Service\", \"memberName\": \"unused\", \"kind\": \"method\", \"sourceFile\": \"Service.kt\", \"confidence\": \"medium\", \"reason\": \"TEST_ONLY\"}]")
        appendLine()
        appendLine("${t("complexity")}:")
        appendLine("  [{\"className\": \"com.example.Service\", \"sourceFile\": \"Service.kt\",")
        appendLine("    \"fanOut\": 12, \"fanIn\": 5, \"distinctOutgoingClasses\": 4, \"distinctIncomingClasses\": 3,")
        appendLine("    \"outgoingByClass\": [{\"className\": \"com.example.Repo\", \"callCount\": 5}],")
        appendLine("    \"incomingByClass\": [{\"className\": \"com.example.Controller\", \"callCount\": 3}]}]")
        appendLine()
        appendLine("${t("cycles")}:")
        appendLine("  [{\"packages\": [\"api\", \"service\"],")
        appendLine("    \"edges\": [{\"from\": \"api\", \"to\": \"service\",")
        appendLine("      \"classEdges\": [{\"source\": \"api.Controller\", \"target\": \"service.Service\"}]}]}]")
        appendLine()
        appendLine("${t("metrics")}:")
        appendLine("  {\"totalClasses\": 42, \"packageCount\": 8, \"averageFanIn\": 3.2, \"averageFanOut\": 5.1,")
        appendLine("   \"cycleCount\": 1, \"deadClassCount\": 3, \"deadMethodCount\": 7,")
        appendLine("   \"topHotspots\": [{\"file\": \"Service.kt\", \"revisions\": 25, \"totalChurn\": 340}]}")
        appendLine()
        appendLine("${t("find-string-constant")}:")
        appendLine("  [{\"className\": \"com.example.Service\", \"methodName\": \"connect\", \"value\": \"http://localhost:8080\", \"sourceFile\": \"Service.kt\"}]")
        appendLine()
        appendLine("${t("annotations")}:")
        appendLine("  [{\"className\": \"com.example.MyController\", \"sourceFile\": \"MyController.kt\",")
        appendLine("    \"classAnnotations\": [\"RestController\"],")
        appendLine("    \"methods\": [{\"method\": \"getUsers\", \"annotations\": [\"GetMapping\"]}]}]")
        appendLine()
        appendLine("${t("changed-since")}:")
        appendLine("  {\"changedClasses\": [{\"className\": \"com.example.Service\", \"sourceFile\": \"Service.kt\",")
        appendLine("    \"callers\": [{\"className\": \"com.example.Controller\", \"method\": \"handle\"}]}],")
        appendLine("   \"unresolvedFiles\": [\"build.gradle.kts\"]}")
        appendLine()
        appendLine("${t("context")}:")
        appendLine("  {\"classDetail\": {\"className\": \"...\", \"sourceFile\": \"...\", ...},")
        appendLine("   \"callers\": [{\"method\": \"...\", \"children\": [...]}],")
        appendLine("   \"callees\": [{\"method\": \"...\", \"children\": [...]}],")
        appendLine("   \"implementors\": [{\"className\": \"...\", \"sourceFile\": \"...\"}],")
        appendLine("   \"implementedInterfaces\": [\"...\"]}")
        appendLine()
        appendLine("${t("distance")}:")
        appendLine("  [{\"source\": \"com.example.api\", \"target\": \"com.example.persistence\", \"distance\": 2, \"deps\": 5}]")
        appendLine()
        appendLine("${t("strength")}:")
        appendLine("  [{\"source\": \"com.example.api\", \"target\": \"com.example.model\", \"strength\": \"MODEL\", \"contract\": 1, \"model\": 2, \"functional\": 0, \"totalDeps\": 3}]")
        appendLine()
        appendLine("${t("balance")}:")
        appendLine("  [{\"source\": \"com.example.api\", \"target\": \"com.example.persistence\", \"strength\": \"FUNCTIONAL\", \"distance\": 3, \"sourceVolatility\": 12, \"targetVolatility\": 8, \"verdict\": \"DANGER\", \"suggestion\": \"...\"}]")
        appendLine()
        appendLine("${t("size")}:")
        appendLine("  [{\"file\": \"services/UserService.kt\", \"lines\": 61}, {\"file\": \"domain/Domain.kt\", \"lines\": 22}]")
        appendLine()
        appendLine("${t("rename-param")}:")
        appendLine("  {\"preview\": false, \"param\": \"limit\", \"newName\": \"maxResults\",")
        appendLine("   \"changes\": [{\"filePath\": \"/src/main/kotlin/Service.kt\", \"diff\": [\"- limit: Int\", \"+ maxResults: Int\"]}]}")
        appendLine()
        appendLine("${t("rename-method")}:")
        appendLine("  {\"preview\": false, \"method\": \"find\", \"newName\": \"search\",")
        appendLine("   \"changes\": [{\"filePath\": \"/src/main/kotlin/Service.kt\", \"diff\": [\"- fun find(\", \"+ fun search(\"]}]}")
        appendLine()
        appendLine("${t("move-class")}:")
        appendLine("  {\"preview\": false, \"className\": \"com.example.services.UserService\", \"newPackage\": \"com.example.domain\", \"newName\": \"AccountService\",")
        appendLine("   \"changes\": [{\"filePath\": \"/src/main/kotlin/Service.kt\", \"diff\": [\"- package com.example.services\", \"+ package com.example.domain\"]}]}")
        appendLine()
        appendLine("${t("rename-property")}:")
        appendLine("  {\"preview\": false, \"property\": \"fullName\", \"newName\": \"displayName\",")
        appendLine("   \"changes\": [{\"filePath\": \"/src/main/kotlin/UserProfile.kt\", \"diff\": [\"- val fullName: String\", \"+ val displayName: String\"]}]}")
        appendLine()
        appendLine("Empty Results:")
        appendLine("  When a query returns no results, JSON/LLM output uses a wrapper with hints:")
        appendLine("  {\"results\":[],\"hints\":[\"Try -Pmethods=true to include method-level annotations\"]}")
        appendLine("  The hints array contains actionable suggestions. It may be empty: {\"results\":[],\"hints\":[]}")
        appendLine("  TEXT output appends hints as plain text lines after the message.")
    }

    private fun generateExtraction(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        appendLine("=== code-navigator: Extracting Output ===")
        appendLine()
        val buildToolNote = when (tool) {
            BuildTool.GRADLE -> "When using ${p("llm", "true")} or ${p("format", "json")}, Gradle mixes its own output (task headers,\nwarnings, build status) into stdout. To handle this, output is wrapped with markers:"
            BuildTool.MAVEN -> "When using ${p("llm", "true")} or ${p("format", "json")}, Maven may mix its own output\ninto stdout. To handle this, output is wrapped with markers:"
        }
        appendLine(buildToolNote)
        appendLine()
        appendLine("  ---CNAV_BEGIN---")
        appendLine("  [{\"className\":\"...\"}]")
        appendLine("  ---CNAV_END---")
        appendLine()
        appendLine("Extract the JSON between markers:")
        appendLine("  ${u("list-classes", p("format", "json"))} | sed -n '/CNAV_BEGIN/,/CNAV_END/p'")
        appendLine()
        appendLine("Or define a shell helper to reduce noise:")
        val helperName = "cnav"
        val helperExample = when (tool) {
            BuildTool.GRADLE -> "  $helperName() { ./gradlew \"\$@\" | sed -n '/CNAV_BEGIN/,/CNAV_END/p'; }"
            BuildTool.MAVEN -> "  $helperName() { mvn \"\$@\" | sed -n '/CNAV_BEGIN/,/CNAV_END/p'; }"
        }
        appendLine(helperExample)
        appendLine()
        appendLine("--- jq Examples (using $helperName helper) ---")
        appendLine()
        appendLine("Extract class names:")
        appendLine("  $helperName ${t("list-classes")} ${p("format", "json")} | jq '.[].className'")
        appendLine()
        appendLine("Find source file for a class:")
        appendLine("  $helperName ${t("find-class")} ${p("pattern", "Service")} ${p("format", "json")} | jq '.[].sourcePath'")
        appendLine()
        appendLine("Get caller method names:")
        appendLine("  $helperName ${t("find-callers")} ${p("pattern", "save")} ${p("maxdepth", "3")} ${p("format", "json")} | jq '.[].children[].method'")
        appendLine()
        appendLine("List packages that depend on domain:")
        appendLine("  $helperName ${t("package-deps")} ${p("package", "domain")} ${p("reverse", "true")} ${p("format", "json")} | jq '.[].dependents[]'")
        appendLine()
        appendLine("Get interface implementor class names:")
        appendLine("  $helperName ${t("find-interfaces")} ${p("pattern", "Repository")} ${p("format", "json")} | jq '.[].implementors[].className'")
    }

    private fun generateRecommendations(tool: BuildTool): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        appendLine("=== code-navigator: Recommendations ===")
        appendLine()
        appendLine("Practices that complement code-navigator analysis. These are not enforced by the")
        appendLine("plugin — they are habits that make structural analysis more effective over time.")
        appendLine()
        appendLine("--- Code Coverage ---")
        appendLine()
        appendLine("Set up JaCoCo (or equivalent) and review coverage reports regularly. Coverage")
        appendLine("tells you which code paths are exercised by tests — code-navigator tells you which")
        appendLine("code paths are structurally important (${t("rank")}, ${t("complexity")}). Combining both")
        appendLine("reveals the highest-risk gaps: structurally important code with low test coverage.")
        appendLine("Without coverage data, dead code removal and refactoring carry unnecessary risk —")
        appendLine("you can't tell whether a change broke untested behavior.")
        appendLine()
        appendLine("--- Test-Driven Development ---")
        appendLine()
        appendLine("Write tests before writing production code. TDD produces code that is testable by")
        appendLine("design — which directly improves the value of structural analysis. When every class")
        appendLine("has tests, ${t("dead")} results are trustworthy (TEST_ONLY items are real signals, not")
        appendLine("noise from missing tests). When fakes are used at system boundaries instead of mocks,")
        appendLine("${t("find-callers")} and ${t("find-interfaces")} show real dependency structure rather")
        appendLine("than mock wiring. TDD also keeps classes small and focused, which shows up as healthy")
        appendLine("fan-in/fan-out numbers in ${t("complexity")}.")
        appendLine()
        appendLine("--- Structural Analysis Cadence ---")
        appendLine()
        appendLine("Run structural analysis regularly, not just when problems are obvious. A routine")
        appendLine("check catches degradation early:")
        appendLine("  - ${t("cycles")} after adding new package dependencies")
        appendLine("  - ${t("dead")} after removing features or deprecating APIs")
        appendLine("  - ${t("balance")} periodically to catch coupling drift")
        appendLine("  - ${t("hotspots")} + ${t("complexity")} before planning refactoring work")
        appendLine("Trends matter more than absolute numbers. Rising cycle count or fan-out over time")
        appendLine("signals architecture degradation even when individual values look acceptable.")
        appendLine()
        appendLine("--- Commit Discipline ---")
        appendLine()
        appendLine("Separate structural changes (renames, moves, extractions) from behavioral changes")
        appendLine("(new features, bug fixes). Never mix them in a single commit. This makes git history")
        appendLine("analysis (${t("hotspots")}, ${t("coupling")}, ${t("churn")}) more accurate —")
        appendLine("structural-only commits won't inflate churn counts or create false coupling signals.")
        appendLine("It also makes each commit independently verifiable: structural changes should pass")
        appendLine("all existing tests with no new behavior, behavioral changes should have new tests.")
        appendLine()
        appendLine("--- Architecture Conformance ---")
        appendLine()
        appendLine("Define layer rules in .cnav-layers.json and run ${t("layer-check")} to enforce them.")
        appendLine("This catches dependency violations (e.g., domain depending on infrastructure) at")
        appendLine("analysis time rather than code review time. Start with a starter config:")
        appendLine("  ${u("layer-check", tool.param("init", "true"))}")
        appendLine("Then refine the layers to match your intended architecture. Run ${t("layer-check")}")
        appendLine("as part of your regular analysis cadence or CI pipeline to prevent violations from")
        appendLine("accumulating.")
    }

    private fun StringBuilder.appendSectionDirectory(tool: BuildTool) {
        val p = { name: String, value: String -> tool.param(name, value) }
        fun u(goal: String, vararg params: String) = tool.usage(goal, *params)

        appendLine("--- More Detail ---")
        appendLine()
        appendLine("Run with ${p("section", "<topic>")} for more detail:")
        appendLine("  ${p("section", "install")}          — snippet to paste into AGENTS.md / CLAUDE.md")
        appendLine("  ${p("section", "setup")}            — permissions and environment setup")
        appendLine("  ${p("section", "workflow")}         — step-by-step analysis workflow")
        appendLine("  ${p("section", "interpretation")}   — heuristics for reading results")
        appendLine("  ${p("section", "schemas")}          — JSON output schemas per task")
        appendLine("  ${p("section", "extraction")}       — extracting output, jq examples")
        appendLine("  ${p("section", "recommendations")} — practices that complement structural analysis")
        appendLine("Run ${u("help")} for full parameter documentation.")
    }

    private fun StringBuilder.appendTroubleshooting(tool: BuildTool) {
        val cmd = when (tool) {
            BuildTool.GRADLE -> "./gradlew"
            BuildTool.MAVEN -> "mvn"
        }
        appendLine("--- Troubleshooting ---")
        appendLine()
        appendLine("If bytecode-based tasks fail with compilation or cache errors:")
        appendLine("  1. Stop the daemon:   $cmd --stop")
        appendLine("  2. Clear Kotlin cache: rm -rf build/kotlin")
        appendLine("  3. Retry with clean:   $cmd clean <task>")
    }

    private val HELP_GOALS = setOf("help", "agent-help", "config-help")
    private val FORMAT_PARAM_NAMES = setOf("format", "llm")

    private fun StringBuilder.appendTaskReference(tool: BuildTool) {
        val compilationTasks = TaskRegistry.ALL_TASKS
            .filter { it.requiresCompilation && it.goal !in HELP_GOALS }
        val gitTasks = TaskRegistry.ALL_TASKS
            .filter { it.category == TaskCategory.GIT_HISTORY }
        val sourceTasks = TaskRegistry.ALL_TASKS
            .filter { it.category == TaskCategory.SOURCE }
        val helpTasks = TaskRegistry.ALL_TASKS
            .filter { it.goal in HELP_GOALS }

        for (task in compilationTasks) {
            appendTaskLine(task, tool)
        }
        appendLine()
        appendLine("  Git history (no compilation needed):")
        for (task in gitTasks) {
            appendTaskLine(task, tool)
        }
        if (sourceTasks.isNotEmpty()) {
            appendLine()
            appendLine("  Source analysis (no compilation needed):")
            for (task in sourceTasks) {
                appendTaskLine(task, tool)
            }
        }
        appendLine()
        appendLine("  Help:")
        for (task in helpTasks) {
            appendLine("  ${padTo(task.taskName(tool), 22)}${task.description}")
        }
    }

    private fun StringBuilder.appendTaskLine(task: TaskDef, tool: BuildTool) {
        val taskName = task.taskName(tool)
        val nonFormatParams = task.params.filter { it.name !in FORMAT_PARAM_NAMES }
        val paramStr = nonFormatParams.joinToString(" ") { param ->
            val rendered = param.render(tool)
            if (param.defaultValue != null) "[$rendered]" else rendered
        }
        val line = if (paramStr.isEmpty()) {
            "  ${padTo(taskName, 22)}${task.description}"
        } else {
            "  ${padTo(taskName, 22)}${padTo(task.description, 36)}$paramStr"
        }
        appendLine(line)
    }

    private fun StringBuilder.appendGlobalParameters(tool: BuildTool) {
        appendLine("  ${padTo(TaskRegistry.LLM.render(tool), 28)}Compact, token-efficient output (all tasks)")
        appendLine("  ${padTo(TaskRegistry.FORMAT.render(tool), 28)}Machine-readable JSON output (all tasks)")
        appendLine()

        val tasksByParam = buildMap<String, MutableList<TaskDef>> {
            for (task in TaskRegistry.ALL_TASKS) {
                for (param in task.params) {
                    if (param.name !in FORMAT_PARAM_NAMES) {
                        getOrPut(param.name) { mutableListOf() }.add(task)
                    }
                }
            }
        }

        val allParams = TaskRegistry.ALL_TASKS
            .flatMap { it.params }
            .filter { it.name !in FORMAT_PARAM_NAMES }
            .distinctBy { it.name }

        for (param in allParams) {
            val tasks = tasksByParam[param.name] ?: continue
            val rendered = param.render(tool)

            val defaultsByValue = tasks.groupBy { it.effectiveDefault(param) }
            val (taskList, defaultSuffix) = if (defaultsByValue.size == 1) {
                val value = defaultsByValue.keys.single()
                val allTaskNames = tasks.joinToString(", ") { it.taskName(tool) }
                allTaskNames to (value?.let { ", default: $it" } ?: "")
            } else {
                val baseDefault = param.defaultValue
                val baseTasks = defaultsByValue[baseDefault] ?: emptyList()
                val baseTaskNames = baseTasks.joinToString(", ") { it.taskName(tool) }

                val parts = defaultsByValue.entries
                    .sortedBy { entry -> if (entry.key == baseDefault) 0 else 1 }
                    .mapNotNull { (value, tasksForValue) ->
                        value ?: return@mapNotNull null
                        val taskNames = tasksForValue.joinToString(", ") { it.taskName(tool) }
                        if (value == baseDefault) {
                            "default: $value"
                        } else {
                            "$taskNames: default: $value"
                        }
                    }
                val suffix = if (parts.isNotEmpty()) ", ${parts.joinToString("; ")}" else ""
                baseTaskNames to suffix
            }

            appendLine("  ${padTo(rendered, 28)}${param.description} ($taskList$defaultSuffix)")
        }
    }

    private fun padTo(s: String, width: Int): String =
        if (s.length >= width) "$s " else s.padEnd(width)
}
