package no.f12.codenavigator

import no.f12.codenavigator.registry.BuildTool
import no.f12.codenavigator.registry.ParamDef
import no.f12.codenavigator.registry.TaskDef
import no.f12.codenavigator.registry.TaskRegistry

object HelpText {
    fun generate(tool: BuildTool = BuildTool.GRADLE): String = buildString {
        val t = { goal: String -> tool.taskName(goal) }
        val p = { name: String, value: String -> tool.param(name, value) }
        val pf = { name: String -> tool.paramFlag(name) }
        fun pd(param: ParamDef<*>, description: String? = null, task: TaskDef? = null) = paramDoc(param, tool, description, task)
        fun examples(task: TaskDef) {
            for (line in task.renderExamples(tool)) {
                appendLine("    $line")
            }
        }

        appendLine("=== code-navigator plugin ===")
        appendLine()
        appendLine("All tasks support ${p("format", "json")} for machine-readable JSON output.")
        appendLine()
        appendLine("--- Pattern Matching ---")
        appendLine()
        appendLine("All pattern parameters are Java regex, case-insensitive, and matched as substrings.")
        appendLine("Simple class names work because of substring matching: 'Owner' matches")
        appendLine("'org.springframework.samples.petclinic.owner.Owner'.")
        appendLine("FQN patterns with escaped dots also work: 'owner\\.Owner' matches the full path.")
        appendLine()
        appendLine("CamelCase shorthand: at camelCase boundaries, .* is inserted automatically.")
        appendLine("  OwnCont  →  Own.*Cont  (matches OwnerController, OwnerContentService, etc.)")
        appendLine()
        appendLine("Parameters with camelCase enhancement: pattern, owner-class, type")
        appendLine("  These auto-expand camelCase boundaries into .* wildcards.")
        appendLine()
        appendLine("Plain regex parameters (no camelCase expansion): method, field, filter, exclude")
        appendLine("  These are matched as-is. The find-string-constant 'pattern' is also plain regex.")
        appendLine()
        appendLine("Available tasks:")
        appendLine()
        appendLine("  ${t("help")}")
        appendLine("    Shows this help text.")
        examples(TaskRegistry.HELP)
        appendLine()
        appendLine("  ${t("list-classes")}")
        appendLine("    Lists all classes in the project and their source files.")
        appendLine("    Scans both main and test source sets by default.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Filter classes by regex (camelCase-aware)")}")
        appendLine("      ${pd(TaskRegistry.JAR, "Scan a JAR file instead of project classes")}")
        examples(TaskRegistry.LIST_CLASSES)
        appendLine()
        appendLine("  ${t("find-class")}")
        appendLine("    Searches for classes matching a regex pattern.")
        appendLine("    Matches against both class name and source file path (case-insensitive).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names and source paths")}")
        appendLine("      ${pd(TaskRegistry.JAR, "Scan a JAR file instead of project classes")}")
        examples(TaskRegistry.FIND_CLASS)
        appendLine()
        appendLine("  ${t("find-symbol")}")
        appendLine("    Searches for symbols (methods, fields) matching a regex pattern.")
        appendLine("    Matches against package, class name, symbol name, and source file (case-insensitive).")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class generated methods.")
        appendLine("    Output columns: Package | Class | Symbol | Kind | Source File")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against symbol information")}")
        appendLine("      ${pd(TaskRegistry.JAR, "Scan a JAR file instead of project classes")}")
        examples(TaskRegistry.FIND_SYMBOL)
        appendLine()
        appendLine("  ${t("find-callers")}")
        appendLine("    Shows who calls a given method, displayed as an indented tree.")
        appendLine("    Builds a call graph from compiled code, then walks callers transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CALL_PATTERN)}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of caller tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC)}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only callers from production or test source set")}")
        examples(TaskRegistry.FIND_CALLERS)
        appendLine()
        appendLine("  ${t("find-callees")}")
        appendLine("    Shows what a method calls, displayed as an indented tree.")
        appendLine("    Builds a call graph from compiled code, then walks callees transitively.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.CALL_PATTERN)}")
        appendLine("      ${pd(TaskRegistry.MAXDEPTH, "Maximum depth of callee tree")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC)}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only callees from production or test source set")}")
        examples(TaskRegistry.FIND_CALLEES)
        appendLine()
        appendLine("  ${t("class-detail")}")
        appendLine("    Shows class signature: fields, methods, superclass, and implemented interfaces.")
        appendLine("    Filters out constructors, synthetic methods, property accessors, and data class boilerplate.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names")}")
        appendLine("      ${pd(TaskRegistry.JAR, "Scan a JAR file instead of project classes")}")
        examples(TaskRegistry.CLASS_DETAIL)
        appendLine()
        appendLine("  ${t("find-interfaces")}")
        appendLine("    Finds classes that implement a given interface.")
        appendLine("    Builds an interface-to-implementors map from compiled code.")
        appendLine("    By default, both main and test source sets are scanned.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against interface names")}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only implementors from production or test source set")}")
        examples(TaskRegistry.FIND_INTERFACES)
        appendLine()
        appendLine("  ${t("type-hierarchy")}")
        appendLine("    Shows the type hierarchy for classes matching a pattern.")
        appendLine("    Walks supertypes upward (superclass chain + interfaces, recursively) and")
        appendLine("    shows implementors downward (classes implementing matched interfaces).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class/interface names")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        examples(TaskRegistry.TYPE_HIERARCHY)
        appendLine()
        appendLine("  ${t("package-deps")}")
        appendLine("    Shows package-level dependencies — which packages call into which other packages.")
        appendLine("    Aggregates the call graph by package, excluding self-dependencies.")
        appendLine("    Without ${p("package", "<regex>")}, shows all packages. With ${p("package", "<regex>")}, filters to matching packages.")
        appendLine("    With ${p("reverse", "true")}, shows reverse dependencies (who depends on each package).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("package"), "Regex to match against package names")}")
        appendLine("      ${pd(TaskRegistry.PACKAGE_DEPS.paramByName("reverse"), "Show reverse dependencies (incoming instead of outgoing)")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        examples(TaskRegistry.PACKAGE_DEPS)
        appendLine()
        appendLine("  ${t("find-usages")}")
        appendLine("    Finds project references to external types or methods.")
        appendLine("    Scans compiled code for method calls, field accesses, and type references")
        appendLine("    matching the specified owner-class/method or type. Owner-aware — distinguishes")
        appendLine("    same-named methods on different types. Finds Kotlin property accessors by")
        appendLine("    their compiled name (e.g., getMonthNumber for .monthNumber).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("owner-class"), "FQN of type — matches method call and field owners")}")
        appendLine("      ${pd(TaskRegistry.METHOD, "Specific method/field name on the owner")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("field"), "Field/property name — also matches getter/setter/is-prefixed accessors")}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("type"))}")
        appendLine("      ${pd(TaskRegistry.FIND_USAGES.paramByName("outside-package"), "Exclude callers inside this package (show only external usages)")}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC)}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only usages from production or test source set")}")
        appendLine("      ${pd(TaskRegistry.GROUP_BY, "Collapse results to one line per source file with a reference count")}")
        appendLine("      * Provide either 'owner-class' or 'type'. Use 'type' for comprehensive search.")
        appendLine("      * 'method' and 'field' are mutually exclusive. 'field' requires 'owner-class'.")
        examples(TaskRegistry.FIND_USAGES)
        appendLine()
        appendLine("  ${t("dsm")}")
        appendLine("    Shows a Dependency Structure Matrix (DSM) — a compact grid view of inter-package")
        appendLine("    dependencies. Row depends on column; cells show reference counts. Highlights cyclic")
        appendLine("    dependencies with class-level detail.")
        appendLine("    By default, both main and test source sets are scanned. External dependencies (JDK, libraries)")
        appendLine("    are automatically filtered out.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-depth"))}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("dsm-html"))}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycles"))}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("cycle"))}")
        appendLine("      ${pd(TaskRegistry.DSM.paramByName("root-package"))}")
        examples(TaskRegistry.DSM)
        appendLine()
        appendLine("  ${t("cycles")}")
        appendLine("    Detects dependency cycles using Tarjan's SCC (Strongly Connected Components) algorithm.")
        appendLine("    Unlike '${t("dsm")} ${p("cycles", "true")}' which only finds pairwise bidirectional edges (A<->B),")
        appendLine("    this finds true multi-node cycles (A->B->C->A). Shows class-level edges for each cycle.")
        appendLine("    By default, both main and test source sets are scanned.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("dsm-depth"))}")
        appendLine("      ${pd(TaskRegistry.CYCLE_DETECTION.paramByName("root-package"))}")
        examples(TaskRegistry.CYCLE_DETECTION)
        appendLine()
        appendLine("  ${t("rank")}")
        appendLine("    Ranks types by structural importance using PageRank on the call graph.")
        appendLine("    Types that are called by many important types score higher. Useful for")
        appendLine("    identifying core abstractions, god classes, and critical dependencies.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only types from production or test source set")}")
        examples(TaskRegistry.RANK)
        appendLine()
        appendLine("  ${t("dead")}")
        appendLine("    Finds potential dead code — classes and methods never referenced by other project code.")
        appendLine("    Reports classes with no incoming type-level references and methods with no cross-class callers.")
        appendLine("    Kotlin noise (data class boilerplate, companion objects, coroutine inner classes,")
        appendLine("    bridge methods, static initializers) is automatically filtered out.")
        appendLine("    Results are 'potential' dead code — reflection-based usage cannot be detected statically.")
        appendLine("    Each result includes a confidence level:")
        appendLine("      HIGH   = unreferenced in both production and test code")
        appendLine("      MEDIUM = unreferenced in production but referenced in test code")
        appendLine("      LOW    = has annotations (likely invoked via reflection/framework)")
        appendLine("    Framework presets distinguish entry-point vs modifier annotations:")
        appendLine("      Entry-point annotations (e.g. @GetMapping, @Scheduled) → excluded from results.")
        appendLine("      Modifier annotations (e.g. @Transactional, @Cacheable) → reported with LOW confidence.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("filter"))}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude"), "Exclude results matching this regex (e.g. entry points, generated packages)")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("classes-only"))}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("exclude-annotated"))}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Scope dead code analysis: prod = test refs don't count, test = find dead test infrastructure")}")
        appendLine("      ${pd(TaskRegistry.DEAD.paramByName("treat-as-dead"))}")
        examples(TaskRegistry.DEAD)
        appendLine()
        appendLine("  ${t("find-string-constant")}")
        appendLine("    Searches for string constants in compiled code matching a regex pattern.")
        appendLine("    Finds hardcoded strings — useful for")
        appendLine("    finding URLs, SQL fragments, configuration keys, log messages, and other literals.")
        appendLine("    Pattern matching is case-insensitive.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.FIND_STRING_CONSTANT.paramByName("pattern"))}")
        examples(TaskRegistry.FIND_STRING_CONSTANT)
        appendLine()
        appendLine("  ${t("annotations")}")
        appendLine("    Finds classes and methods annotated with names matching a regex pattern.")
        appendLine("    Scans class-level annotations by default. Use ${p("methods", "true")} to also search")
        appendLine("    method-level annotations.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against annotation simple names")}")
        appendLine("      ${pd(TaskRegistry.ANNOTATIONS.paramByName("methods"))}")
        examples(TaskRegistry.ANNOTATIONS)
        appendLine()
        appendLine("  ${t("complexity")}")
        appendLine("    Shows fan-in/fan-out complexity for classes matching a regex pattern.")
        appendLine("    Fan-out: how many calls go from this class to other classes (outgoing coupling).")
        appendLine("    Fan-in: how many calls come into this class from other classes (incoming coupling).")
        appendLine("    Without ${TaskRegistry.PATTERN.render(tool)}, shows all project classes sorted by fan-out descending.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Class name regex to analyze")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        appendLine("      ${pd(TaskRegistry.COMPLEXITY.paramByName("detail"))}")
        appendLine("      ${pd(TaskRegistry.COLLAPSE_LAMBDAS)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Show only classes from production or test source set")}")
        examples(TaskRegistry.COMPLEXITY)
        appendLine()
        appendLine("  ${t("metrics")}")
        appendLine("    Quick project health snapshot combining structural analysis and git history.")
        appendLine("    Shows: total classes, packages, average fan-in/fan-out, cycle count,")
        appendLine("    dead classes/methods, and top hotspots.")
        appendLine("    By default, both main and test source sets are scanned.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.TOP, "Number of hotspots to show")}")
        appendLine("      ${pd(TaskRegistry.NO_FOLLOW)}")
        appendLine("      ${pd(TaskRegistry.METRICS.paramByName("exclude-annotated"))}")
        appendLine("      ${pd(TaskRegistry.METRICS.paramByName("treat-as-dead"), "Treat framework-annotated code as potentially dead")}")
        appendLine("      ${pd(TaskRegistry.SCOPE, "Scope structural analysis to production or test source set")}")
        appendLine("      ${pd(TaskRegistry.METRICS.paramByName("root-package"))}")
        examples(TaskRegistry.METRICS)
        appendLine()
        appendLine("  ${t("changed-since")}")
        appendLine("    Shows the blast radius of changes since a git ref — finds changed source files,")
        appendLine("    maps them to compiled classes, and shows their callers (who is affected).")
        appendLine("    Requires both git (to find changed files) and compilation (to resolve call graph).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.REF)}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY, "Filter callers to project classes only")}")
        examples(TaskRegistry.CHANGED_SINCE)
        appendLine()
        appendLine("  ${t("context")}")
        appendLine("    Gathers full context for a class in a single call: class detail (fields, methods,")
        appendLine("    superclass, interfaces), callers tree, callees tree, interface implementors, and")
        appendLine("    implemented interfaces. Reduces multiple task invocations to one.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PATTERN, "Regex to match against class names")}")
        appendLine("      ${pd(TaskRegistry.CONTEXT_MAXDEPTH, "Maximum depth of caller/callee trees")}")
        appendLine("      ${pd(TaskRegistry.PROJECTONLY)}")
        appendLine("      ${pd(TaskRegistry.FILTER_SYNTHETIC)}")
        appendLine("      ${pd(TaskRegistry.SCOPE)}")
        examples(TaskRegistry.CONTEXT)
        appendLine()
        appendLine("  ${t("distance")}")
        appendLine("    Computes the structural distance between coupled packages using the package")
        appendLine("    tree hierarchy. High distance with many dependencies indicates long-range coupling.")
        appendLine("    Uses the same bytecode scanning as DSM; distance = tree hops from source to target package.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.DISTANCE.paramByName("dsm-depth"))}")
        appendLine("      ${pd(TaskRegistry.TOP, task = TaskRegistry.DISTANCE)}")
        examples(TaskRegistry.DISTANCE)
        appendLine()
        appendLine("  ${t("strength")}")
        appendLine("    Classifies each inter-package dependency edge by integration strength —")
        appendLine("    the type of knowledge shared between packages (Balanced Coupling theory).")
        appendLine("    Three levels: CONTRACT (depends on interface/abstract class), MODEL (depends")
        appendLine("    on data class/record), FUNCTIONAL (depends on concrete class). When a package")
        appendLine("    pair has edges at multiple levels, the strongest (most coupled) level is reported.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.STRENGTH.paramByName("dsm-depth"))}")
        appendLine("      ${pd(TaskRegistry.TOP, task = TaskRegistry.STRENGTH)}")
        examples(TaskRegistry.STRENGTH)
        appendLine()
        appendLine("  ${t("balance")}")
        appendLine("    Composite balanced coupling analysis (combines ${t("strength")}, ${t("distance")}, ${t("volatility")})")
        appendLine("    into a single verdict per package pair. Requires both compiled code (bytecode) and git history.")
        appendLine("    Verdicts: BALANCED (good modularity), TOLERABLE (poor modularity but low volatility),")
        appendLine("    OVER_ENGINEERED (loosely coupled nearby packages), DANGER (tight coupling + high distance + volatility).")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.PACKAGE_FILTER)}")
        appendLine("      ${pd(TaskRegistry.INCLUDE_EXTERNAL)}")
        appendLine("      ${pd(TaskRegistry.BALANCE.paramByName("dsm-depth"))}")
        appendLine("      ${pd(TaskRegistry.TOP, task = TaskRegistry.BALANCE)}")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS)}")
        examples(TaskRegistry.BALANCE)
        appendLine()
        appendLine("  ${t("layer-check")}")
        appendLine("    Checks hexagonal architecture layer conformance against a config file (.cnav-layers.json).")
        appendLine("    The config defines ordered layers (outermost first, innermost last).")
        appendLine("    Each layer has name patterns (globs like *Controller, *Service, *Repository, *).")
        appendLine("    First matching pattern wins. Each layer may depend only on layers below it.")
        appendLine("    Peer dependencies (same layer) are forbidden by default (peerLimit controls this).")
        appendLine("    Kotlin file classes (Kt suffix) and test classes (Test suffix) are automatically")
        appendLine("    matched to the layer of their base name — no need to add *Kt or *Test variants.")
        appendLine("    Layers with testInfrastructure: true allow test classes to depend on them from any layer.")
        appendLine("    Classes that don't match any specific pattern can be caught by a * catch-all layer.")
        appendLine("    Use ${p("init", "true")} to generate a starter config from detected class name patterns.")
        appendLine("    Non-zero exit code on violations, usable in CI.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.LAYER_CONFIG)}")
        appendLine("      ${pd(TaskRegistry.INIT)}")
        examples(TaskRegistry.LAYER_CHECK)
        appendLine()
        appendLine("  ${t("agent-help")}")
        appendLine("    Shows detailed instructions for AI coding agents on how to use code-navigator effectively.")
        appendLine("    Includes recommended workflows, task selection guidance, and tips for optimal results.")
        examples(TaskRegistry.AGENT_HELP)
        appendLine()
        appendLine("  ${t("config-help")}")
        appendLine("    Lists all available configuration parameters with defaults")
        appendLine("    and which tasks they apply to.")
        examples(TaskRegistry.CONFIG_HELP)
        appendLine()
        appendLine("--- Git History Analysis Tasks ---")
        appendLine()
        appendLine("These tasks analyze git history and do NOT require compilation.")
        appendLine("All share the parameter: ${TaskRegistry.AFTER.render(tool)} (default: ${TaskRegistry.AFTER.defaultValue})")
        appendLine("Git rename tracking is enabled by default (-M flag). Use ${TaskRegistry.NO_FOLLOW.render(tool)} to disable it.")
        appendLine()
        appendLine("  ${t("hotspots")}")
        appendLine("    Ranks files by change frequency. The most-changed files are where development")
        appendLine("    effort concentrates — priority refactoring targets if they also have structural problems.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.HOTSPOTS)
        appendLine()
        appendLine("  ${t("coupling")}")
        appendLine("    Finds files that change together in the same commits — implicit dependencies invisible")
        appendLine("    in call graphs. Complements structural ${t("package-deps")} with behavioral coupling data.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-shared-revs"))}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("min-coupling"))}")
        appendLine("      ${pd(TaskRegistry.COUPLING.paramByName("max-changeset-size"))}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.COUPLING)
        appendLine()
        appendLine("  ${t("code-age")}")
        appendLine("    Measures time since last modification per file. Stable old code is good;")
        appendLine("    frequently-changing old code with structural problems is a hotspot.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.CODE_AGE)
        appendLine()
        appendLine("  ${t("authors")}")
        appendLine("    Number of distinct contributors per file. More developers on a module means")
        appendLine("    larger communication challenges. High author counts correlate with defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.AUTHORS)
        appendLine()
        appendLine("  ${t("churn")}")
        appendLine("    Measures lines added/deleted per file. Pre-release churn is a good predictor")
        appendLine("    of post-release defects.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.CHURN)
        appendLine()
        appendLine("  ${t("volatility")}")
        appendLine("    Aggregates file-level git history to the package level. Shows which packages")
        appendLine("    change most often — a key dimension of Balanced Coupling analysis.")
        appendLine("    High-volatility packages need loose coupling; low-volatility ones can tolerate tighter coupling.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.AFTER)}")
        appendLine("      ${pd(TaskRegistry.MIN_REVS)}")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        examples(TaskRegistry.VOLATILITY)
        appendLine()
        appendLine("--- Source Analysis Tasks ---")
        appendLine()
        appendLine("These tasks scan source files directly and do NOT require compilation.")
        appendLine()
        appendLine("  ${t("size")}")
        appendLine("    Lists source files (Kotlin/Java) by line count, largest first.")
        appendLine("    Use ${p("over", "<N>")} to filter out small files.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        appendLine("      ${pd(TaskRegistry.OVER)}")
        examples(TaskRegistry.SIZE)
        appendLine()
        appendLine("  ${t("duplicates")}")
        appendLine("    Detects duplicate code blocks across source files using token-based matching.")
        appendLine("    Use ${p("scope", "prod")} to focus on production code, ${p("scope", "test")} for test code only.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.TOP)}")
        appendLine("      ${pd(TaskRegistry.MIN_TOKENS)}")
        appendLine("      ${pd(TaskRegistry.SCOPE)}")
        examples(TaskRegistry.DUPLICATES)
        appendLine()
        appendLine("  ${t("rename-param")}")
        appendLine("    Renames a method parameter and updates all named-argument call sites.")
        appendLine("    Applies changes by default; use ${pf("preview")} to preview without writing.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.RENAME_CLASS)}")
        appendLine("      ${pd(TaskRegistry.RENAME_METHOD)}")
        appendLine("      ${pd(TaskRegistry.RENAME_PARAM)}")
        appendLine("      ${pd(TaskRegistry.RENAME_NEW_NAME)}")
        appendLine("      ${pd(TaskRegistry.PREVIEW)}")
        examples(TaskRegistry.RENAME_PARAM_TASK)
        appendLine()
        appendLine("  ${t("rename-method")}")
        appendLine("    Renames a method and updates all call sites, including implementations of interface methods.")
        appendLine("    Applies changes by default; use ${pf("preview")} to preview without writing.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.RENAME_CLASS)}")
        appendLine("      ${pd(TaskRegistry.RENAME_METHOD)}")
        appendLine("      ${pd(TaskRegistry.RENAME_NEW_NAME)}")
        appendLine("      ${pd(TaskRegistry.PREVIEW)}")
        examples(TaskRegistry.RENAME_METHOD_TASK)
        appendLine()
        appendLine("  ${t("move-class")} (alias: ${t("rename-class")})")
        appendLine("    Moves a class to a different package and/or renames it, updating all references.")
        appendLine("    Both ${p("from", "")} and ${p("to", "")} are required fully qualified class names.")
        appendLine("    Applies changes by default; use ${pf("preview")} to preview without writing.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.MOVE_FROM)}")
        appendLine("      ${pd(TaskRegistry.MOVE_TO)}")
        appendLine("      ${pd(TaskRegistry.PREVIEW)}")
        examples(TaskRegistry.MOVE_CLASS_TASK)
        appendLine()
        appendLine("  ${t("rename-property")}")
        appendLine("    Renames a property (val/var) and updates all access sites, constructor call sites, and copy() calls.")
        appendLine("    Applies changes by default; use ${pf("preview")} to preview without writing.")
        appendLine("    Parameters:")
        appendLine("      ${pd(TaskRegistry.RENAME_CLASS)}")
        appendLine("      ${pd(TaskRegistry.RENAME_PROPERTY)}")
        appendLine("      ${pd(TaskRegistry.RENAME_NEW_NAME)}")
        appendLine("      ${pd(TaskRegistry.PREVIEW)}")
        examples(TaskRegistry.RENAME_PROPERTY_TASK)
        appendLine()
        appendLine("--- Useful Combinations ---")
        appendLine()
        appendLine("These task combinations answer common questions that no single task covers:")
        appendLine()
        appendLine("  Refactoring targets: ${t("hotspots")} + ${t("complexity")} + ${t("cycles")}")
        appendLine("    Files that change often, have high fan-out, and sit in dependency cycles.")
        appendLine()
        appendLine("  Architecture overview: ${t("dsm")} + ${t("package-deps")} + ${t("cycles")}")
        appendLine("    Structural map of the codebase: dependency matrix, per-package edges, and tangles.")
        appendLine()
        appendLine("  Change risk: ${t("changed-since")} + ${t("find-callers")}")
        appendLine("    Blast radius of recent changes, then trace deeper into affected call chains.")
        appendLine()
        appendLine("  Code review context: ${t("hotspots")} + ${t("authors")} + ${t("churn")}")
        appendLine("    Behavioral history: what changes often, who owns it, how much churn.")
        appendLine()
        appendLine("  Coupling health: already available as ${t("balance")} (combines strength × distance × volatility).")
        appendLine()
        appendLine("If you are an AI coding agent, run ${TaskRegistry.AGENT_HELP.renderExamples(tool).first()} for optimized guidance.")
    }

    private fun paramDoc(param: ParamDef<*>, tool: BuildTool, description: String? = null, task: TaskDef? = null): String {
        val rendered = param.render(tool)
        val effectiveDefault = task?.effectiveDefault(param) ?: param.defaultValue
        val annotation = when {
            effectiveDefault != null -> "(optional, default: $effectiveDefault)"
            param.flag -> "(optional)"
            else -> "(required)"
        }
        val desc = description ?: param.description
        return "$rendered  $annotation $desc"
    }
}
